CC = gcc

CFLAGS = -Wall -g

LDFLAGS = 

TARGETS = t1 chmod umask chown truncate link remove rename symlink utime mkdir rmdir readdir chdir

.PHONY: all clean

all: $(TARGETS)

clean:
	rm -f *.o *~ $(TARGETS) *.file

